AWSTemplateFormatVersion: '2010-09-09'

Description: >

  To deploy AWS Parameter Store

  Last Modified: Oct 2021

Parameters:
  ProductName:
    Description: Name of the team resources are created for.
    Type: String
    Default: Test

  Platform:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: DEV
    AllowedValues: [DEV, TST, QA, STG, PRD]

Resources:
  CloudwatchAgentParameterStore:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub SSMParameter-${ProductName}-${Platform}
      DataType: text
      Tier: Advanced
      Type: String
      Description: SSM Parameter containing configuration of the application.
      Tags:
        Name: !Sub SSMParameter-${ProductName}-${Platform}
        Platform: !Sub ${Platform}
      Value: "{\"name\": \"my-project\", \"metrics_collection_interval\":30}"