AWSTemplateFormatVersion: '2010-09-09'

Description: >

  To deploy AWS S3 bucket

  Last Modified: Oct 2021

Parameters:
  ProductName:
    Description: Name of the team resources are created for.
    Type: String
    Default: Test

  Platform:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: DEV
    AllowedValues: [DEV, TST, QA, STG, PRD]

Resources:
  S3LogBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: datastore-bucket-${ProductName}-${Platform}
      Tags:
          - Key: Name
            Value: datastore-bucket-${ProductName}-${Platform}
          - Key: Platform
            Value: !Sub ${Platform}