AWSTemplateFormatVersion: '2010-09-09'

Description: >

  To deploy AWS AppConfig

  Last Modified: Oct 2021

Parameters:
  ProductName:
    Description: Name of the team resources are created for.
    Type: String
    Default: Test

  Platform:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: DEV
    AllowedValues: [DEV, TST, QA, STG, PRD]

  ConfigurationProfileVersion:
    Description: Configuration json file Version ID from S3 bucket
    Type: String

  AppConfigRoleArn:
    Description: RoleArn for Appconfig.
    Type: String

  S3AppconfigBucketName:
    Description: Enter the Cloud Formation template S3 Bucket name.
    Type: String

  ConfigProfileJSONFile:
    Description: Enter the application configuration as JSON file.
    Type: String

Resources:
  MyAppApplication:
      Type: AWS::AppConfig::Application
      Properties:
        Name: !Sub AppConfig-Application-${ProductName}-${Platform}
        Description: "Application"
        Tags:
          - Key: Name
            Value: !Sub AppConfig-Application-${ProductName}-${Platform}
          - Key: Platform
            Value: !Sub ${Platform}

  MyAppEnvironment:
    Type: AWS::AppConfig::Environment
    Properties:
      ApplicationId: !Ref MyAppApplication
      Name: !Sub AppConfig-Environment-${ProductName}-${Platform}
      Description: "Environment"
      Tags:
        - Key: Name
          Value: !Sub AppConfig-Environment-${ProductName}-${Platform}
        - Key: Platform
          Value: !Sub ${Platform}

  MyAppDeploymentStrategy:
    Type: AWS::AppConfig::DeploymentStrategy
    Properties:
      Name: !Sub AppConfig-DeploymentStrategy-${ProductName}-${Platform}
      Description: "APP deployment strategy."
      DeploymentDurationInMinutes: 0
      FinalBakeTimeInMinutes: 0
      GrowthFactor: 100
      GrowthType: LINEAR
      ReplicateTo: NONE
      Tags:
        - Key: Name
          Value: !Sub AppConfig-DeploymentStrategy-${ProductName}-${Platform}
        - Key: Platform
          Value: !Sub ${Platform}

  MyAppConfigurationProfile:
    Type: AWS::AppConfig::ConfigurationProfile
    Properties:
      ApplicationId: !Ref MyAppApplication
      Name: !Sub AppConfig-ConfigurationProfile-${ProductName}-${Platform}
      Description: "Application configuration profile"
      RetrievalRoleArn: !Sub ${AppConfigRoleArn}
      LocationUri: !Sub s3://${S3AppconfigBucketName}/${Platform}/${ConfigProfileJSONFile}
      Tags:
        - Key: Name
          Value: !Sub AppConfig-ConfigurationProfile-${ProductName}-${Platform}
        - Key: Platform
          Value: !Sub ${Platform}

  MyAppDeployment:
    Type: AWS::AppConfig::Deployment
    DependsOn: MyAppConfigurationProfile
    Properties:
      ApplicationId: !Ref MyAppApplication
      EnvironmentId: !Ref MyAppEnvironment
      DeploymentStrategyId: !Ref MyAppDeploymentStrategy
      ConfigurationProfileId: !Ref MyAppConfigurationProfile
      ConfigurationVersion: !Ref ConfigurationProfileVersion
      Description: 'AppConfig deployment'
      Tags:
        - Key: Name
          Value: !Sub AppConfig-Deployment-${ProductName}-${Platform}
        - Key: Platform
          Value: !Sub ${Platform}

Outputs:
  MyAppConfigurationProfile:
    Description: "Application configuration profile"
    Value: !Ref MyAppConfigurationProfile
    Export:
      Name: !Sub AppConfig-ConfigurationProfile-${ProductName}-${Platform}